### PR TITLE
Fix and improve crud test

### LINKED ISSUE #38: Actor CRUD test unnecessarily includes database operations in it
Currently the actor CRUD test creates database backed actors. This adds unnecessary variance in the statistics via database and network transmission latencies.

It should instead create synthetic actor with `Actor.create(data, {temporary:true})` so it measures only the actual processing time instead of also network and server latency.

### LINKED ISSUE #39: Actor CRUD test assumes "npc" type exists
Currently the CRUD tests assumes all systems have "npc" type actor. This is blatantly false. Either the test should iterate through all actual types, or let users choose one at start of the test.

The actual types can be fetched from the array at `game.system.template.Actor.types` or via keys in `CONFIG.Actor.sheetClasses`

### PR DESCRIPTION
**Pull request by mkahvi**
Implements actor type selection ~~and synthetic actor toggle~~. Also small improvements to related code thrown in.

Fixes #39

### CODE REVIEW

File: module/classes/DevModePerformance.mjs [hunk 1]
```diff
@@ -17,14 +17,18 @@ export class DevModePerformance {
     });
   }
 
-  static actorCRUDTest = async (iterations = 1000) => {
-    console.log('running test with iterations:', `${iterations}`, !!iterations, iterations || 1000);
+  static actorCRUDTest = async (type, iterations = 1000, synthetic) => {
```
Comment (akrigline) [inline module/classes/DevModePerformance.mjs:20]: Since this is getting more complex, lets destructure an object as the first parameter here. That will help this 'self-document' as well.

```suggestion
  static actorCRUDTest = async ({ type, iterations = 1000, synthetic } = {}) => {
```

File: module/classes/DevModeConfig.mjs [hunk 2]
```diff
@@ -188,9 +192,12 @@ export class DevModeConfig extends FormApplication {
...
           case 'actorCRUD': {
-            const inputVal = html.find('input[name="actorCrudIterations"]').val();
-            console.log('inputVal', inputVal);
-            return DevModePerformance.actorCRUDTest(inputVal || undefined);
+            const form  = new FormDataExtended(event.currentTarget.closest('form')).toObject();
+            const actorType = form.actorCrudType;
+            const iterations = form.actorCrudIterations;
+            const synthetic = form.actorCrudSynthetic;
+            console.log('CRUD', { actorType, iterations, synthetic });
+            return DevModePerformance.actorCRUDTest(actorType, iterations || undefined, synthetic);
```
Comment (akrigline) [inline module/classes/DevModeConfig.mjs:200]: If we use an object as the param for `actorCRUDTest`, we might be able to pass the output of `formData` directly into this method.

Comment (mkahvi) [reply module/classes/DevModeConfig.mjs:200]: Giving form data directly would give really ugly parameter names, unless the CRUD test is given its own form. That gets into rather large redesigns of the settings dialog.

Comment (mkahvi) [reply module/classes/DevModeConfig.mjs:200]: I think I had an idea for a solution.

**Comment by mkahvi** [comment]
I removed synthetic option as I discovered it wasn't used correctly, and after I fixed it, I also realized Foundry explodes on .update() calls to such. So even if the idea is great (IMO), Foundry doesn't support it.

File: module/classes/DevModePerformance.mjs [hunk 3]
```diff
@@ -17,14 +17,17 @@ export class DevModePerformance {
     });
   }
 
-  static actorCRUDTest = async (iterations = 1000) => {
-    console.log('running test with iterations:', `${iterations}`, !!iterations, iterations || 1000);
+  static actorCRUDTest = async (type, iterations = 1000) => {
```
Comment (akrigline) [inline module/classes/DevModePerformance.mjs:20]:
```suggestion
  static actorCRUDTest = async ({ type, iterations = 1000} = {}) => {
```
by feeding it the object output from `FormDataExtended`, this will need to destructure that object

File: module/classes/DevModePerformance.mjs [hunk 4]
```diff
@@ -17,14 +17,17 @@ export class DevModePerformance {
...
+    if (!game.system.template.Actor.types.includes(type)) return console.error(type, "is invalid actor type");
+    // Force some defaults
+    iterations ||= 1000;
```
Comment (akrigline) [inline module/classes/DevModePerformance.mjs:23]:
```suggestion
```

This is handled in the params and shouldn't be necessary here.

File: module/classes/DevModePerformance.mjs (hunk 3 above)
Comment (mkahvi) [reply module/classes/DevModePerformance.mjs:20]: I thought I did that already... I honestly had problems with git that might've lost that.

**Review by akrigline — CHANGES_REQUESTED** [review]
Shame that the temporary thing didn't work out. Still thanks for setting up the better system support

**Review by akrigline — APPROVED** [review]
