### PR TITLE
Fix template-cache patch in Foundry v10

### LINKED ISSUE #52: Error on JournalEntryPage editor rendering in 10.275
**Environment Details**
- Foundry Core Version: 10.275
- System & Version:  multiple
- OS & Browser: Node/Win10/Firefox
- Hosting:  Self-hosted

**Describe the bug**
Error thrown when module enabled and edit button on JournalEntryPage clicked, see screenshot
Error does not occur when module is not enabled, error occurs under multiple systems including dnd5e 2.0.0-alpha2

**To Reproduce**
1. Open JournalEntry
2. Select Page
3. Click to edit
4. See error in console, no editor window renders

**Expected behavior**
Editor window opens

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ben**
Fixes #52. v10's `getTemplate` takes an extra parameter, which wasn't being passed through the patch.

### CODE REVIEW

File: module/patches/getTemplate.mjs [hunk 1]
```diff
@@ -12,7 +12,7 @@ export default function setupDisableTemplateCache() {
    * is rendered.
    * AKA: Poor Man's Hot-Reload
    */
-  async function _devModeGetTemplate(path) {
+  async function _devModeGetTemplate(path, id) {
```
Comment (akrigline) [inline module/patches/getTemplate.mjs:15]:
```suggestion
  async function _devModeGetTemplate(path, ...args) {
```

File: module/patches/getTemplate.mjs [hunk 2]
```diff
@@ -21,7 +21,7 @@ export default function setupDisableTemplateCache() {
       delete _templateCache[path];
     }
 
-    return _getTemplate(path);
+    return _getTemplate(path, id);
```
Comment (akrigline) [inline module/patches/getTemplate.mjs:24]:
```suggestion
    return _getTemplate(path, ...args);
```
might this be more futureproof?
not sure how this responds when there are no further args

**Comment by ben** [comment]
Yes, of course that's better. Thanks!
